services:
    database:
        image: mongo
        restart: always
        ports:
            -   "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: loom
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data: